In [1]:
import numpy as np

In [21]:
a=np.array([1,2,3,4])
a1=np.array([1,6,4,4])
np.add(a,a1)

array([2, 8, 7, 8])

In [23]:
print(a+5)
print(a*5)
print(a-5)
print(a/5)
print(a%5)

[6 7 8 9]
[ 5 10 15 20]
[-4 -3 -2 -1]
[0.2 0.4 0.6 0.8]
[1 2 3 4]


In [17]:
print(c)

[2 8 7 6]


In [34]:
ap=np.array([[1,2,3,4],[4,3,5,2]])
ap.shape

(2, 4)

In [33]:
a=np.array([[1,2,3],[3,2,4]])
a.shape

(2, 3)

In [51]:
am=np.array([
    [
        [1,2],[3,2],[5,6]
    ],
     [
        [9,4],[5,3],[3,4]
    ]
    
])

In [52]:
am.shape

(2, 3, 2)

In [58]:
am[0][0][1]+2

4

In [64]:
np.zeros([3,5,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
 np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [75]:
d=np.arange(10,25,2).reshape

In [76]:
d

array([10, 12, 14, 16, 18, 20, 22, 24])

In [88]:
a=np.array([
    [1,2,4,5,6,3,2,2],
    [5,3,4,5,7,8,94,2]
])

In [81]:
a.shape

(2, 3)

In [95]:
# Reshaping
a
c=a.reshape((4,2,2,1,1,1))

In [96]:
c

array([[[[[[ 1]]],


         [[[ 2]]]],



        [[[[ 4]]],


         [[[ 5]]]]],




       [[[[[ 6]]],


         [[[ 3]]]],



        [[[[ 2]]],


         [[[ 2]]]]],




       [[[[[ 5]]],


         [[[ 3]]]],



        [[[[ 4]]],


         [[[ 5]]]]],




       [[[[[ 7]]],


         [[[ 8]]]],



        [[[[94]]],


         [[[ 2]]]]]])

In [98]:
p=np.array([[[1,2,3],
           [4,5,6],
            [6,4,5]]])
p.flatten()

array([1, 2, 3, 4, 5, 6, 6, 4, 5])

In [99]:
p=np.array([[[1,2,3],
           [4,5,6],
            [6,4,5]]])
p.reshape(9)

array([1, 2, 3, 4, 5, 6, 6, 4, 5])

## hstack vstack

In [103]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,3])
np.hstack((a,b))

array([1, 2, 3, 4, 4, 5, 6, 3])

In [105]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,3])
np.vstack((a))

array([[1],
       [2],
       [3],
       [4]])

In [111]:
p=a.reshape(2,2,1,1)



(2, 2, 1, 1)

# Random

In [5]:
np.random.rand(1,3)

array([[0.18454867, 0.5313089 , 0.29366373]])

In [6]:
np.random.rand(2,2)

array([[0.0023583 , 0.18503343],
       [0.33195201, 0.61590102]])

In [8]:
np.random.rand(1,3,4)

array([[[0.06796562, 0.69595755, 0.93587056, 0.22955017],
        [0.08628028, 0.39869966, 0.67706418, 0.34743353],
        [0.90058993, 0.15438197, 0.42685427, 0.36496595]]])

In [16]:
np.random.randint(2,100,size=[2,2])

array([[80, 10],
       [15, 82]])

In [23]:
np.random.randint(0,4,size=[10,10])

array([[3, 3, 3, 2, 3, 3, 0, 1, 1, 1],
       [3, 3, 3, 0, 2, 0, 3, 0, 1, 2],
       [1, 3, 0, 2, 0, 1, 3, 3, 3, 1],
       [2, 1, 3, 0, 0, 2, 1, 3, 2, 2],
       [1, 0, 3, 0, 0, 1, 1, 1, 2, 2],
       [0, 2, 0, 2, 2, 1, 0, 1, 0, 2],
       [2, 0, 0, 2, 2, 3, 3, 1, 0, 1],
       [2, 1, 3, 0, 2, 0, 0, 0, 1, 1],
       [3, 1, 3, 0, 2, 0, 1, 1, 2, 2],
       [0, 1, 3, 3, 0, 0, 0, 3, 0, 3]])

In [21]:
np.random.choice(['a','e','i','o','u'],size=10)

array(['e', 'u', 'u', 'u', 'o', 'i', 'i', 'u', 'a', 'e'], dtype='<U1')

In [35]:
"".join( np.random.choice([1,2,3,4,5,6,7,8,9,'@','#','%','a','e','i','o','u','m','l'],size=10))

'597247%94%'

In [45]:
# with prob
print("".join (np.random.choice(['a','e','i','o','u'],size=10,p=[0.2,0.4,0.1,0.1,0.2]))

eeaeiieeoa


In [52]:
# with prob
print("".join (np.random.choice(['a','e','i','o','u'],size=10,p=[0.2,0.5,0.2,0,0.1])))

iieaeeieea


## Statistical Functions

In [54]:
ap=np.array([1,2,34,2,1,2,3,4,5,6,7,23,12,34,654,323,543,23,2,12,343,54,])
np.min(ap)
np.max(ap)

654

In [55]:
np.amax(ap)

654

In [65]:
ap=np.array([[1,2,34],[2,1,2],[3,4,5],[6,7,23],[12,34,654],[323,543,23],[2,12,343]])
np.amax(ap,axis=1)

array([ 34,   2,   5,  23, 654, 543, 343])

In [66]:
ap=np.array([1,2,34,2,1,2,3,4,5,6,7,23,12,34,654,323,543,23,2,12,343,54,])
np.mean(ap)

95.0

In [67]:
np.median(ap)

9.5

In [69]:
np.std(ap)

184.9717423136449

In [70]:
np.var(ap)

34214.545454545456

In [87]:
aq=[1,2,3,1,2,4]
np.mean(aq)


2.1666666666666665

In [88]:
np.std(aq)

1.0671873729054748

In [84]:
pl=np.var(aq)

In [90]:
am=[[1,2,3],[1,2,4]]
np.std(am)


1.0671873729054748

## Matrix

In [91]:
import scipy.linalg as slin

In [101]:
p=np.array([[1,223,3],
             [4,5,6]
           ,[7,8,234]])
slin.det(p)
print(np.trace(p))

240


In [97]:
c=np.random.randint(0,256,size=[10,10])
slin.det(c)

5.53080464939432e+21

In [100]:
print(c)
np.transpose(c)

[[181 181 109  90  72 253  89  19  49  40]
 [  9  53  30   5   1  82  89  15 105  55]
 [147 156  74 187  64  48 234 176  82  36]
 [221 253 188 243  93  15 217 249 192  71]
 [149  50   0  65 178 245 251  45  96 151]
 [ 76 127  74  19 197  89 214  63 106 104]
 [190 189 232 135 232  43 238 183 162  65]
 [240 161  74  73 115 165  49  80  16  88]
 [ 58  84 179  38 146  41  60  32   8 141]
 [ 27 247   3 207  98 136 251 224 194  58]]


array([[181,   9, 147, 221, 149,  76, 190, 240,  58,  27],
       [181,  53, 156, 253,  50, 127, 189, 161,  84, 247],
       [109,  30,  74, 188,   0,  74, 232,  74, 179,   3],
       [ 90,   5, 187, 243,  65,  19, 135,  73,  38, 207],
       [ 72,   1,  64,  93, 178, 197, 232, 115, 146,  98],
       [253,  82,  48,  15, 245,  89,  43, 165,  41, 136],
       [ 89,  89, 234, 217, 251, 214, 238,  49,  60, 251],
       [ 19,  15, 176, 249,  45,  63, 183,  80,  32, 224],
       [ 49, 105,  82, 192,  96, 106, 162,  16,   8, 194],
       [ 40,  55,  36,  71, 151, 104,  65,  88, 141,  58]])

In [103]:
p=np.array([[1,223,3],
             [4,5,6]
           ,[7,8,234]])
slin.inv(p)


array([[-5.65954935e-03,  2.63093383e-01, -6.67342584e-03],
       [ 4.50948050e-03, -1.07440643e-03, -3.02649698e-05],
       [ 1.51324849e-05, -7.83358302e-03,  4.47417137e-03]])

In [119]:
a=np.array([[2,3,5,4],[3,2,1,4],[4,3,1,4]])
b=np.array([[112,12,12,12],
            [13,12,43,12],
            [112,32,432,12]])
print(a*b)

[[224  36  60  48]
 [ 39  24  43  48]
 [448  96 432  48]]


In [120]:
np.mean(a*b)

128.83333333333334